/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `antlr`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    antlr("org.antlr:antlr4:4.13.2")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

val antlrPackage = "com.tedneward.lolcode.parser"

tasks.register<Copy>("copyGrammarSource") {
    from(file("../../lolcode.g4"))
    into(file("src/main/antlr/"))
}
tasks.generateGrammarSource {
    dependsOn("copyGrammarSource")

    maxHeapSize = "64m"
    arguments = arguments + 
        listOf("-visitor", 
               "-long-messages",
               "-package", antlrPackage)
    outputDirectory = file("${project.buildDir}/generated/sources/main/java/antlr")
}
sourceSets {
    main {
        java {
            srcDir(tasks.generateGrammarSource)
        }
    }
}
